name: Test push check action

on: 
    push:
        branches: "*"

jobs:
    Check_Initial_Condition:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls